genbioconsortium/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings


admin.site.site_header = 'GenBioConsortium ADMIN'
admin.site.index_title = 'GenBioConsortium'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('membership/', include('membership.urls', namespace='membership')),
    path('precongress/', include('precongress.urls', namespace='precongress')),
    path('fullcongress/', include('fullcongress.urls', namespace='fullcongress')),
    path("payment/", include("payment.urls")),
]

membership/urls.py
from django.urls import path
from . import views

from . views import membershipCategory, CongressCategory



app_name = 'membership'
urlpatterns = [
    path('member_cat/', membershipCategory.as_view(), name='precongress_cat'),
     path('member_cat/', CongressCategory.as_view(), name='congress_cat'),
    path('<int:category_id>/', views.membership_registration, name='membership_registration'),
    path('payment_method/', views.payment_method, name='payment_method'),
    path('congress/members/', views.congress_members, name='congress_members'),

    
]

payment/urls.py
from django.urls import path
from .views import payment_canceled, create_paypal_order, paypal_webhook


from . import views


app_name = 'payment'
urlpatterns = [
    path('payment_done/', views.payment_done, name='payment_done'),
    path('canceled/', payment_canceled, name='payment_canceled'),
    path('create_paypal_order', create_paypal_order, name='create_paypal_order'),
    path('paypal_webhook', views.paypal_webhook, name='paypal_webhook'),
    
]

users/urls.py
from django.urls import path
from .import views

from django.contrib.auth import views as auth_view

urlpatterns = [
    # path('', views.home, name='home'),
    path('', views.register, name="register"),
    path('login', views.customized_login, name='login'),
    path('logout', views.customized_logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('profile/<username>', views.profile, name='profile'),
    path("password_change", views.password_change, name="password_change"),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm, name='password_reset_confirm'),
    path('manage', views.manage, name='manage'),
]

membership/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django_countries.fields import CountryField

from django.utils import timezone

CustomUser = get_user_model()

class RegistrationType(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class  MembershipCategory(models.Model):
    title = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    registration_type = models.ForeignKey(RegistrationType, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title


class MembershipRegistration(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    registration_type = models.ForeignKey(RegistrationType, on_delete=models.CASCADE, null=True)
    membership_category = models.ForeignKey(MembershipCategory, on_delete=models.CASCADE, null=True)
    institution = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    country = CountryField()
    occupation = models.CharField(max_length=100)
    terms_checkbox = models.BooleanField(default=False)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.registration_type.title} - {self.first_name} {self.last_name}"


class Payment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    registration_type = models.ForeignKey(RegistrationType, on_delete=models.CASCADE ,null=True)
    registration_category = models.ForeignKey(MembershipCategory, on_delete=models.CASCADE, null=True)
    membership_registration = models.ForeignKey(MembershipRegistration, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    full_name = models.CharField(max_length=60)
    payment_id = models.CharField(max_length=100)
    email = models.EmailField()
    payment_status = models.CharField(max_length=30)
    gross_pay = models.DecimalField(max_digits=8, decimal_places=2)
    paypal_fee = models.DecimalField(max_digits=8, decimal_places=2)
    net_pay = models.DecimalField(max_digits=8, decimal_places=2)
    payer_id = models.CharField(max_length=100)

    def __str__(self):
        return f"Payment for {self.membership_registration} - Transaction ID: {self.transaction_id}"

membership/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from .models import MembershipRegistration
from users.models import CustomUser

class MembershipRegistrationForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}), label='First Name')
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}), label='Last Name')
    email = forms.EmailField(max_length=254, widget=forms.EmailInput(attrs={'class': 'form-control'}), label='Email')
    membership = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}), label='Membership Type')
    institution = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}), label='Institution')
    city = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}), label='City')
    country = CountryField().formfield(
        widget=CountrySelectWidget(attrs={'class': 'form-control'}),
        label='Country',
    )
    occupation = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}), label='Occupation')
    terms_checkbox = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}), label='I agree to the terms and conditions', error_messages={'required': 'You must agree to the terms and conditions'})
    membership_price = forms.DecimalField(max_digits=6, decimal_places=2, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}), label='Membership Price')
    user = forms.ModelChoiceField(queryset=CustomUser.objects.all(), widget=forms.HiddenInput(), required=False)

    class Meta:
        model = MembershipRegistration
        fields = ['first_name', 'last_name', 'email', 'membership', 'institution', 'city', 'country', 'occupation', 'terms_checkbox', 'membership_price', 'user']
        widgets = {'terms': forms.CheckboxInput(attrs={'required': True})}

membership/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import MembershipCategory
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from .forms import MembershipRegistrationForm
from django.contrib import messages
from django.contrib.auth.models import User
from .models import *
from pyisemail import is_email
import pycountry
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator




# Create your views here.
class membershipCategory(ListView):
    model = MembershipCategory
    template_name = 'membership/precongress_cat.html'
    context_object_name = 'categories'

    def get_queryset(self):
        # Get the registration type for Pre Conference
        pre_conference_type = RegistrationType.objects.get(title='Pre Congress')

        # Filter the membership categories by the Pre Conference registration type
        queryset = MembershipCategory.objects.filter(registration_type=pre_conference_type)

        return queryset

class CongressCategory(ListView):
    model = MembershipCategory
    template_name = 'membership/congress_cat.html'
    context_object_name = 'categories'

    def get_queryset(self):
        # Get the registration type for Pre Conference
        conference = RegistrationType.objects.get(title='Congress')

        # Filter the membership categories by the Pre Conference registration type
        queryset = MembershipCategory.objects.filter(registration_type=conference)

        return queryset


def is_student_email(email):
    if is_email(email, check_dns=True, diagnose=True):
        domain = email.split('@')[1]
        country_codes = [country.alpha_2 for country in pycountry.countries]
        if domain.endswith('.edu') or domain.endswith('.ac') or domain.endswith('.students') or any(domain.endswith('.' + code.lower()) for code in country_codes):
            return True
    return False



def membership_registration(request, category_id):
    category = get_object_or_404(MembershipCategory, id=category_id)
    user = request.user
    try:
        membership = MembershipRegistration.objects.get(user=user)
        initial_data = {
            'membership': category.title,
            'membership_price': category.price
        }
        form = MembershipRegistrationForm(request.POST or None, instance=membership, initial=initial_data)
    except MembershipRegistration.DoesNotExist:
        initial_data = {
            'membership': category.title,
            'membership_price': category.price,
            'user': user,
        }
        form = MembershipRegistrationForm(request.POST or None, initial=initial_data)
        
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = user
            
            # Validate student email for "Students/Post-doctoral/Early career scientists" category
            if category.title == 'Students/Post-doctoral/Early career scientists':
                email = form.cleaned_data.get('email')
                if not is_student_email(email):
                    form.add_error('email', 'Invalid student email')
                    return render(request, 'membership/member_reg.html', {'form': form, 'category': category})
            
            instance.save()
            messages.success(request, 'Membership registration details updated successfully')
            return redirect('membership:payment_method')
        
    context = {
        'form': form,
        'category': category
    }
    return render(request, 'membership/member_reg.html', context)

def is_superuser(user):
    return user.is_superuser

@login_required
@user_passes_test(is_superuser)
def congress_members(request):
    members = MembershipRegistration.objects.all()
    paginator = Paginator(members, 10)  # Set the number of items per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'membership/manage.html', {'page_obj': page_obj})




def payment_method(request):
    user_id = request.user.id
    try:
        membership_registration = MembershipRegistration.objects.get(user_id=user_id)
        # retrieve the necessary information from the membership_registration object
        context = {
            'membership': membership_registration
        }
        return render(request, 'membership/payment_method.html', context)
    except MembershipRegistration.DoesNotExist:
        return redirect('membership:member_reg')
    
    

membership/templates/membership/manage.html
{% extends 'users/base_admin.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<style>
.pagination {
    display: flex;
    justify-content: center;
    margin-top: 20px;
}

.pagination a {
    margin: 0 5px;
    color: #333;
    text-decoration: none;
    display: inline-block;
    padding: 6px 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
}

.pagination .current-page {
    font-weight: bold;
    color: #000;
    display: inline-block;
    padding: 6px 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    background-color: #007bff;
    color: #fff;
}
</style>

<div class="container mt-5">
    <h3 class="text-center">Congress Members</h3>
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Full Name</th>
                <th>Email</th>
                <th>Institution</th>
                <th>City</th>
                <th>Country</th>
                <th>Occupation</th>
                <th>Membership</th>
                <th>Price</th>
                <th>Paid</th>
                <th>Registered At</th>
            </tr>
        </thead>
        <tbody>
            {% for member in page_obj %}
            <tr>
                <td>{{ member.first_name }} {{ member.last_name }}</td>
                <td>{{ member.email }}</td>
                <td>{{ member.institution }}</td>
                <td>{{ member.city }}</td>
                <td>{{ member.get_country_display }}</td>
                <td>{{ member.occupation }}</td>
                <td>{{ member.membership }}</td>
                <td>{{ member.membership_price }}</td>
                <td>{% if member.paid %}Yes{% else %}No{% endif %}</td>
                <td>{{ member.created_at }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Pagination links -->
    <div class="pagination">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">previous</a>
        {% endif %}
        <span class="current-page btn btn-primary">{{ page_obj.number }}</span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary">next</a>
        {% endif %}
    </div>
</div>
{% endblock content %}

membership/templates/membership/member_cat.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container">
    <h3 class="text-center">Membership Registration Fee</h3>
    <div class="row">
      {% for category in categories %}
        <div class="col-md-4" style="height: 300px;">
          <div class="card text-center">
            <div class="card-header">
              <p>{{ category.title }}</p>
              <p><b>$: {{ category.price }}</b></p>
            </div>
            <div class="card-body">
              
            </div>
            <div class="card-footer text-center">
              <a href="{% url 'membership:membership_registration' category.id %}" class="btn btn-success">Register</a>

            </div>
          </div>
        </div>
        {% empty %}
            <div class="col-md-12">
              <p>No Membership found.</p>
            </div>
          {% endfor %}
      </div>
    </div>
  
{% endblock content %}

membership/templates/membership/member_reg.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
   <div class="card py-5">
    <div class="content-section col-lg-12 col-md-12 col-sm-12 tutorial-style" style="min-height:65vh;">
        <legend class="border-bottom mb-4">Member Registration Details:</legend>
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-8">
                    <div class="form-row">
                        <div class="form-group col-md-4 mb-0">
                            {{ form.first_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                            {{ form.last_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                            {{ form.email|as_crispy_field }}
                        </div>
                    </div> 
                    <div class="form-row">
                        <div class="form-group col-md-4 mb-0">
                            {{ form.country|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                            {{ form.city|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                            {{ form.occupation|as_crispy_field }}
                        </div>
                    </div> 
                    <div class="form-row">
                        <div class="form-group col-md-4 mb-0">
                            {{ form.institution|as_crispy_field }}
                        </div>
                       
                    </div> 
                    <div class="form-row">
                        
                        <div class="form-group col-sm-12 col-md-6 mb-0">
                            {{ form.terms_checkbox|as_crispy_field }}
                        </div>
                       
                    </div> 

                </div>
                <div class="col-sm-4">
                 
                <div class="card text-center">
                    <div class="form-row">
                        <div class="form-group col-md-10 mb-0">
                            {{ form.membership|as_crispy_field }}
                        </div>
                       
                        <div class="form-group col-md-10 mb-0">
                            {{ form.membership_price|as_crispy_field }}
                        </div>
                    </div>
                </div>
                <hr>
                </div>
              </div>
              <div class="form-group col-md-6 justify-content-center">
                <div class="text-center ">
                    <button class="btn btn-success text-center" type="submit">Submit</button>
                </div>
            </div>
              </form>
              
    </div>
   </div>
</div>




{% endblock content %}

membership/templates/membership/payment_method.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container">
    <h3 class="text-center mt-3">Choose your Preferred Payment method</h3>
    <hr>
    <div class="row py-5">
        <div class="col-md-6" style="height: 300px;">
          <div class="card text-center shadow-sm">
            <div class="card-header">
              <h5>Your Membership Details</h5>
              <hr>
           <p><b>Category:</b> {{ membership.membership }}</p>
           <p><b>Fee:</b> ${{ membership.membership_price }}</p>
           <hr>
            </div>
          </div>
          
          </div>
          <div class="col-md-6" style="height: 300px;">
            <div class="card text-center shadow-sm">
            
              <div class="card-body">
                <script src="https://www.paypal.com/sdk/js?client-id=AWweB1Tx8aenCx6x3xeLgQatxoKHZ395o2UBpydjpiQQvnPf5K_Yq-DoS-rXiSPKRwCw8m8p0qcYsHu5&currency=USD"></script>
                                    <!-- Set up a container element for the button -->
                                    <div id="paypal-button-container"></div>
                                    <script>
                                      paypal.Buttons({
                                        
                                        // Order is created on the server and the order id is returned
                                        createOrder() {
                                          return fetch("{% url 'payment:create_paypal_order' %}", {
                                            method: "POST",
                                            headers: {
                                              "Content-Type": "application/json",
                                            },
                                            // use the "body" param to optionally pass additional order information
                                            // like product skus and quantities
                                            body: JSON.stringify({
                                              cart: [
                                                {
                                                  sku: "1st Global Congress On New And Emerging Genetic Biocontrol Technologies",
                                                },
                                              ],
                                            }),
                                          })
                                          .then((response) => response.json())
                                          .then((order) => order.id);
                                        },
                                        // Finalize the transaction on the server after payer approval
                                        
                                                                                onApprove: function(data, actions) {
                                          // Capture the funds from the transaction
                                          return actions.order.capture().then(function(details) {
                                            // Call your server to save the transaction
                                            return fetch("{% url 'payment:paypal_webhook' %}", {
                                              method: 'POST',
                                              headers: {
                                                'Content-Type': 'application/json'
                                              },
                                              body: JSON.stringify({
                                                orderID: data.orderID,
                                                paymentID: details.id
                                              })
                                            })
                                            .then(function(response) {
                                              // Check if the payment was successful
                                              if (response.ok) {
                                                // Redirect the user to a payment done page
                                                window.location.href = "{% url 'payment:payment_done' %}";
                                              } else {
                                                // Handle the error
                                                console.error('Payment failed');
                                              }
                                            })
                                            .catch(function(error) {
                                              // Handle the error
                                              console.error(error);
                                            });
                                          });
                                        }





                                      }).render('#paypal-button-container');
                                    </script>
              </div>
             
            </div>
          </div>
      </div>
    </div>
  
{% endblock content %}

membership/templates/membership/precongress_cat.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <h3 class="text-center">PreCongress Registration Fee</h3>
    <div class="row mt-4">
      {% for category in categories %}
        <div class="col-md-4" style="height: 300px;">
          <div class="card text-center border-0 shadow-sm">
            <div class="card-header">
              <p>{{ category.title }}</p>
              <p><b>$: {{ category.price }}</b></p>
            </div>
            <div class="card-body">
              
            </div>
            <div class="card-footer text-center">
              <a href="{% url 'membership:membership_registration' category.id %}" class="btn btn-success">Register</a>

            </div>
          </div>
        </div>
        {% empty %}
            <div class="col-md-12">
              <p>No Membership found.</p>
            </div>
          {% endfor %}
      </div>
    </div>
  
{% endblock content %}