fullcongress/urls.py
from django.urls import path
from . import views

from . views import *



app_name = 'fullcongress'
urlpatterns = [
    path('fullcongress_cat/', fullcongressCategory.as_view(), name='fullcongress_cat'),
    path('<int:category_id>/', views.membership_registration, name='membership_registration'),
    path('members/', fullcongress_members, name='fullcongress_members'),
    # path('payment_method/', views.payment_method, name='payment_method'),
    
]

genbioconsortium/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings


admin.site.site_header = 'GenBioConsortium ADMIN'
admin.site.index_title = 'GenBioConsortium'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('membership/', include('membership.urls', namespace='membership')),
    path('precongress/', include('precongress.urls', namespace='precongress')),
    path('fullcongress/', include('fullcongress.urls', namespace='fullcongress')),
    path("payment/", include("payment.urls")),
]

membership/urls.py
from django.urls import path
from . import views

from . views import membershipCategory, CongressCategory



app_name = 'membership'
urlpatterns = [
    path('member_cat/', membershipCategory.as_view(), name='precongress_cat'),
     path('member_cat/', CongressCategory.as_view(), name='congress_cat'),
    path('<int:category_id>/', views.membership_registration, name='membership_registration'),
    path('payment_method/', views.payment_method, name='payment_method'),
    path('congress/members/', views.congress_members, name='congress_members'),

    
]

precongress/urls.py
from django.urls import path
from . import views

from . views import *



app_name = 'precongress'
urlpatterns = [
    path('precongress_cat/', precongressCategory.as_view(), name='precongress_cat'),
    path('<int:category_id>/', views.membership_registration, name='membership_registration'),
    path('precongress/users/', precongress_users, name='precongress_users'),
    # path('payment_method/', views.payment_method, name='payment_method'),
    
]

users/urls.py
from django.urls import path
from .import views

from django.contrib.auth import views as auth_view

urlpatterns = [
    # path('', views.home, name='home'),
    path('', views.register, name="register"),
    path('login', views.customized_login, name='login'),
    path('logout', views.customized_logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('profile/<username>', views.profile, name='profile'),
    path("password_change", views.password_change, name="password_change"),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm, name='password_reset_confirm'),
    path('manage', views.manage, name='manage'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    registered_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.username

class UserLoginRecord(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    login_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.login_time}"

@receiver(user_logged_in)
def record_user_login(sender, user, request, **kwargs):
    UserLoginRecord.objects.create(user=user)

users/forms.py
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import PasswordResetForm
from captcha.fields import ReCaptchaField, ReCaptchaV2Checkbox

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'form-control'}),
        label='',
    )
    email = forms.EmailField(
        max_length=254,
        widget=forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'form-control'}),
        label='',
    )
    first_name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={'placeholder': 'Enter First Name', 'class': 'form-control'}),
        label='',
    )
    last_name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={'placeholder': 'Enter Last Name', 'class': 'form-control'}),
        label='',
    )
    password1 = forms.CharField(
        label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control', 'autocomplete': 'new-password'}),
    )
    password2 = forms.CharField(
        label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password', 'class': 'form-control', 'autocomplete': 'new-password'}),
    )

    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username or Email'}),
        label="Username or Email*")

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email']

class CustomSetPasswordForm(SetPasswordForm):
    class Meta:
        model = CustomUser
        fields = ['new_password1', 'new_password2']

class CustomPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(CustomPasswordResetForm, self).__init__(*args, **kwargs)

        # captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())

users/views.py
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.auth import get_user_model
from .forms import UserUpdateForm
from .forms import SetPasswordForm
from .forms import UserRegisterForm
from .token import account_activation_token
from django.contrib.auth.decorators import login_required
from .forms import SetPasswordForm
from django_daraja.mpesa.core import MpesaClient
from django.contrib.auth import authenticate, login
from django.conf import settings
from datetime import timedelta
from django.contrib.auth.decorators import login_required
from .forms import PasswordResetForm
from django.db.models.query_utils import Q
from .forms import SetPasswordForm
from django.contrib.auth.forms import AuthenticationForm
from .decorators import user_not_authenticated
from django.core.mail import EmailMultiAlternatives
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.utils.html import strip_tags
from .forms import UserLoginForm
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import user_passes_test
from .models import *
from django.core.paginator import Paginator



# Create your views here.
def home(request):
    return render(request, 'users/home.html')

def register(request):
   if request.method == "POST":
     form = UserRegisterForm(request.POST)
     if form.is_valid():
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        activateEmail(request, user, form.cleaned_data.get('email'))
        return redirect('register')
     else:
         for error in list(form.errors.values()):
            messages.error(request, error)

        # username = form.cleaned_data.get('username')
        # messages.success(request, f'Account created succesfully for { username}')
        # return redirect('login')
   else:
      form = UserRegisterForm
   return render(request, 'users/register.html',{'form':form})

def activateEmail(request, user, to_email):
    mail_subject = 'Activate your user account.'
    message = render_to_string('users/acc_active_email.html', {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(request, f'Hello {user} , please go to you email {to_email} inbox or check your spam folder for email confirmation and complete the registration.')
    else:
        messages.error(request, f'If you did not receive the email, Please confirm that {to_email} this is your actual mail')

def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(request, 'Thanks for your email confirmation. Log in now ')
        return redirect('login')
    else:
        messages.error(request, 'Activation link is invalid!')
    
    return redirect('login')

def customized_login(request):
    if request.method == "POST":
        form = UserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            if user is not None:
                login(request, user)
                messages.success(request, f"Successfully logged in as {user.username}")
                if user.is_superuser:
                    return redirect("manage")  # Redirect to the manage view for super admins
                else:
                    return redirect("membership:member_cat")  # Redirect to a different view for non-super admins

        else:
            for error in list(form.errors.values()):
                messages.error(request, error) 

    form = UserLoginForm()

    return render(
        request=request,
        template_name="users/login.html",
        context={"form": form}
    )


@login_required
def customized_logout(request):
    logout(request)
    messages.info(request, "Logged out, You may log in again")
    return redirect("login")




@login_required
def profile(request, username):
    if request.method == 'POST':
        user = request.user
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            user_form = form.save()

            messages.success(request, f'{user_form}, Your profile has been updated!')
            return redirect('profile', user_form.username)

        for error in list(form.errors.values()):
            messages.error(request, error)

    user = get_user_model().objects.filter(username=username).first()
    if user:
        form = UserUpdateForm(instance=user)
        return render(request, 'users/profile.html', context={'form': form})

    return redirect("profile")

@login_required
def password_change(request):
    user = request.user
    if request.method == 'POST':
        form = SetPasswordForm(user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your password has been changed")
            return redirect('login')
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    form = SetPasswordForm(user)
    return render(request, 'users/password_reset_confirm.html', {'form': form})


def password_reset_request(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        
        if form.is_valid():
            user_email = form.cleaned_data['email']
            associated_user = get_user_model().objects.filter(Q(email=user_email)).first()
            if associated_user:
               subject = "Password Reset request"
               html_message = render_to_string("users/template_reset_password.html", {
                   'user': associated_user,
                   'domain': get_current_site(request).domain,
                   'uid': urlsafe_base64_encode(force_bytes(associated_user.pk)),
                   'token': account_activation_token.make_token(associated_user),
                   "protocol": 'https' if request.is_secure() else 'http'
                   })
               plain_message = strip_tags(html_message)
               email = EmailMultiAlternatives(subject, plain_message, to=[associated_user.email])
               email.attach_alternative(html_message, "text/html")
               email.send()
               if email.send():
                messages.success(request,"""Password reset has been emailed to you please check your mail""")
            else:
                messages.error(request, "Problem sending reset password email")

            return redirect('login')

        for key, error in list(form.errors.items()):
            if key == 'captcha' and error[0] == 'This field is required.':
                messages.error(request, "You must pass the reCAPTCHA test")
                continue

    form = PasswordResetForm()
    return render(
        request=request, 
        template_name="users/password_reset.html", 
        context={"form": form}
        )
def passwordResetConfirm(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        if request.method == 'POST':
            form = SetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Your password has been set. You may now login")
                return redirect('login')
            else:
                for error in list(form.errors.values()):
                    messages.error(request, error)

        form = SetPasswordForm(user)
        return render(request, 'users/password_reset_confirm.html', {'form': form})
    else:
        messages.error(request, "Link is expired")

    messages.error(request, 'Something went wrong, redirecting back to Homepage')
    return redirect("home")

def is_super_admin(user):
    return user.is_authenticated and user.is_superuser


@login_required(login_url='login')
@user_passes_test(is_super_admin, login_url='login', redirect_field_name=None)
def manage(request):
    users = CustomUser.objects.all()
    login_records = UserLoginRecord.objects.all()

    # Paginate the users
    users_paginator = Paginator(users, 10)  # Display 10 users per page
    users_page_number = request.GET.get('users_page')
    users_page = users_paginator.get_page(users_page_number)

    # Paginate the login records
    login_records_paginator = Paginator(login_records, 10)  # Display 10 login records per page
    login_records_page_number = request.GET.get('login_records_page')
    login_records_page = login_records_paginator.get_page(login_records_page_number)

    return render(request, 'users/manage.html', {'users': users_page, 'login_records': login_records_page})

users/templates/users/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
You may ignore if you did not initiate the registration from African Genetic Biocontrol consortium
{% endautoescape %}

users/templates/users/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>African Genetic Biocontrol Consortium</title>
    <!--Css Style -->
    <link rel="stylesheet" href="{% static 'users/css/main.css' %}" type="text/css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <!--Font Link-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Open+Sans:wght@800&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'users/images/logo200-140x69.png' %}" type="image/x-icon">

    <style>
        /* Add your custom CSS styles for the receipt here */
        body {
            font-family: Arial, sans-serif;
        }
        .receipt {
            margin: 50px auto;
            width: 400px;
            padding: 20px;
            border: 1px solid #ccc;
        }
        .receipt-header {
            text-align: center;
            margin-bottom: 20px;
        }
        .receipt-details {
            margin-bottom: 20px;
        }
        .receipt-details label {
            font-weight: bold;
        }
        .receipt-footer {
            text-align: center;
            margin-top: 20px;
        }
        .print-button {
            text-align: center;
        }
        @media print {
            /* Hide the print button when printing */
            .print-button {
                display: none;
            }
        }
    </style>
</head>
<body>
  </head>
  <body>
  {% load static %}
  {% load bootstrap_icons %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm" id="main-navbar">
    <div class="container">
      <a class="navbar-brand" href="{% url 'login' %}">
        <img src="{% static 'users/images/logo200-140x69.png' %}" alt="">
      </a>
  
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle bg-success text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ user.username }}
            </a>
            <ul class="dropdown-menu dropdown-menu-end border-0 text-center" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'profile' user.username %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'membership:precongress_cat' %}">Pre-Congress Registration</a></li>
                <li><a class="dropdown-item" href="{% url 'membership:congress_cat' %}">Congress Registration</a></li>
                <li><a class="dropdown-item" href="{% url 'fullcongress:fullcongress_cat' %}">Full congress registration</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </li>
          {% else %}
          <li class="nav-item">
            <div class="btn-group" id="my-btn-group">
              <a href="{% url 'register' %}" class="btn btn-success mr-2">Sign Up</a>
              <a href="{% url 'login' %}" class="btn btn-success">Sign In</a>
            </div>                      
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="container mt-3">
    <div class="row">
      <div class="col-12">
        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>              
          </div>
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
        {% block content %}
        {% endblock content %}
      </div>

      <!-- Optional JavaScript; choose one of the two! -->

      <!-- Option 1: Bootstrap Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

      <!-- Option 2: Separate Popper and Bootstrap JS -->
     
  </body>
</html>

users/templates/users/base_admin.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>African Genetic Biocontrol Consortium</title>
    <!--Css Style -->
    <link rel="stylesheet" href="{% static 'users/css/main.css' %}" type="text/css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <!--Font Link-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Open+Sans:wght@800&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'users/images/logo200-140x69.png' %}" type="image/x-icon">

    <style>
        /* Add your custom CSS styles for the receipt here */
        body {
            font-family: Arial, sans-serif;
        }
        .receipt {
            margin: 50px auto;
            width: 400px;
            padding: 20px;
            border: 1px solid #ccc;
        }
        .receipt-header {
            text-align: center;
            margin-bottom: 20px;
        }
        .receipt-details {
            margin-bottom: 20px;
        }
        .receipt-details label {
            font-weight: bold;
        }
        .receipt-footer {
            text-align: center;
            margin-top: 20px;
        }
        .print-button {
            text-align: center;
        }
        @media print {
            /* Hide the print button when printing */
            .print-button {
                display: none;
            }
        }
    </style>
</head>
<body>
  </head>
  <body>
  {% load static %}
  {% load bootstrap_icons %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm" id="main-navbar">
    <div class="container">
      <a class="navbar-brand" href="{% url 'login' %}">
        <img src="{% static 'users/images/logo200-140x69.png' %}" alt="">
      </a>
  
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle bg-success text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ user.username }}
            </a>
            <ul class="dropdown-menu dropdown-menu-end border-0 text-center" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'profile' user.username %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'precongress:precongress_users' %}">Pre-Congress Registration</a></li>
                <li><a class="dropdown-item" href="{% url 'membership:congress_members' %}">Congress Registration</a></li>
                <li><a class="dropdown-item" href="{% url 'fullcongress:fullcongress_members' %}">Full congress registration</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </li>
          {% else %}
          <li class="nav-item">
            <div class="btn-group" id="my-btn-group">
              <a href="{% url 'register' %}" class="btn btn-success mr-2">Sign Up</a>
              <a href="{% url 'login' %}" class="btn btn-success">Sign In</a>
            </div>                      
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="container mt-3">
    <div class="row">
      <div class="col-12">
        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>              
          </div>
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
        {% block content %}
        {% endblock content %}
      </div>

      <!-- Optional JavaScript; choose one of the two! -->

      <!-- Option 1: Bootstrap Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

      <!-- Option 2: Separate Popper and Bootstrap JS -->
     
  </body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Login</h1>
                                    </div>
                                    <form action="" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            {{ form.username }}
                                        </div>
                                        <div class="form-group">
                                            {{ form.password }}
                                        </div>
                                        <div class="form-group">
                                            <input type="checkbox" name="remember_me">Remember Me
                                        </div>
                                        <input type="hidden" name="next" value="{{ request.GET.next }}"/>
                                        <div class="form-group my-3" id="signup-button">
                                            <button class="btn btn-success">Sign in</button>
                                        </div>
                                    </form>
                                    
                                    <hr>
    
                                    <div class="form-group text-center">
                                        <a href="{% url 'register' %}" class="no-style-link">Dont have an Account? Register</a>
                                    </div>
                                    <div class="form-group text-center">
                                        <a href="{% url 'password_reset' %}" class="no-style-link">Forgot your Password? Reset</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                      
                       <form action="" method="POST">
                        {% csrf_token %}
                        <form-group>
                            {{ form|crispy }}
                        </form-group>
                        <div class="form-group my-3 text-center" id="signup-button">
                            <button class="btn btn-primary">Sign Up</button>
                        </div>
                      </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Reset Your Password</h1>
                                    </div>
                                    <form method="POST">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <button class="btn btn-success my-3" type="submit">Reset password</button>
                                    </form>
                                    <hr>
    
                                    <div class="text-center">
                                        <a class="small" href="{% url 'register' %}">
                                            Already have an account? Login!
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}